version: '3.9'

services:
  localhost:3306:
    image: mysql:8
    container_name: jobportal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sahana@123VS
      MYSQL_DATABASE: job_portal
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: jobportal-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/job_portal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sahana@123VS
    depends_on:
      - localhost:3306

volumes:
  mysql-data:
